const languages = {
    "en": {
"Account": "Account",
    "Learn_More": "Learn More",
        "personalInfo": "Personal info",
        "provideDetails": "Provide personal details and how we can reach you",
        "loginSecurity": "Login & security",
        "updatePassword": "Update your password and secure your account",
        "paymentsPayouts": "Payments & payouts",
        "reviewPayments": "Review payments, payouts, coupons, and gift cards",
        "viewWishlist": "View your beloved Wishlist",
        "seeUpcomingTrips": "See your upcoming trips",
      "filterBtnLabel": "Filters",
      "taxesSwitchLabel": "Display total before taxes",
      "stays": "stays",
      "experiences": "experiences",
      "log_in": "log in",
      "sign_up": "sign up",
      "gift_cards": "gift cards",
      "airbnb_your_home": "airbnb your home",
      "Wishlist": "Wishlist",
      "Trips": "Trips",
      "host_exp": "host an experience",
      "messages":"Messages",
      "account": "Account",
      "help_center": "help center",
      "who": "who",
      "addGuests": "add guests",
      "checkOut": "check out",
      "addDate": "add date",
      "checkIn": "check in",
      "where": "where",
      "Where_to":"Where to?",
        "when":"When",
      "searchDest": "Search Destinations",
      "lovedBnb": "One of the most loved homes on Airbnb, according to guests",
      "reviews": "Reviews",
      "hosted": "Hosted by Piavi",
      "hostSpan": "3 months hosting",
      "roomInHome": "Your own room in a home, plus access to shared spaces.",
      "sharedSpaces": "You’ll share parts of the home with other guests.",
      "prvSpace": "This place has a bathroom that’s connected to your room.",
      "grtExp": "100% of recent guests gave the check-in process a 5-star rating.",
      "guestFav": "Guest favorite",
      "oneOfMost": "One of the most loved homes on Airbnb based on ratings, reviews, and reliability",
      "ovrAll": "Overall rating",
      "clean": "Cleanliness",
      "accuracy": "Accuracy",
      "check-in": "Check-in",
      "comm": "Communication",
      "loc": "Location",
      "val": "Value",
      "entire": "Entire",
      "in": "in",
      "guests": "guests",
      "bedrooms": "bedrooms",
      "beds": "beds",
      "baths": "baths",
      "night": "night",
      "adults": "Adults",
      "children": "Children",
      "infants": "Infants",
      "pet": "Pet",
      "notCharged": "You won't be charged yet",
      "totalBefore": "Total before taxes",
      "reserve": "Reserve",
      "showAll": "Show all photos",
      "log_out": "Log out",
      "new_roomInHome": "Room in a home", 
      "new_sharedSpaces": "Shared common spaces",
      "new_prvSpace": "Private attached bathroom",
      "new_grtExp": "Great check-in experience",
      "lockOnDoor": "Lock on bedroom door",
    "wifi": "Wifi",
    "petsAllowed": "Pets allowed",
    "airConditioning": "Air conditioning",
    "longTermStays": "Long-term stays allowed",
    "lakeAccess": "Lake access",
    "freeParking": "Free parking on premises",
    "tv": "TV",
    "securityCameras": "Security cameras on property",
    "cleaningAvailable": "Cleaning available during stay",
    "whatThisPlaceOffers": "What this place offers",
    "showAllAmenities": "Show All Amenities",
    "meetYourHost": "Meet your Host",
    "rating": "Rating",
    "hosting": "Hosting",
    "years": "Years",
    "speaks": "Speaks English, French and Hindi",
    "livesIn": "Lives in Jaipur, India",
    "hostBio": "Hi All, I am Piava Jain C/O Le Pensions Stays & Enterprises Pvt Ltd. By qualification, I am a chartered Accountant from The Institute of Chartered Accountants of India. But at heart, I have always been an entrepreneur. Our team has a collective experience of more than 24 years in hospitality and we love what we do. Le Pension...",
        "anywhere": "Anywhere",
    "anyWeek": "Any week",
    "addGuests": "Add guests",
    "privacy": "Privacy",
    "terms": "Terms",
    "siteMap": "Site map",
    "chooseLangRegion": "Choose a language and region",
    "explore":"Explore",
    "confirmAndPay": "Confirm and Pay",
    "yourTrip": "Your trip",
    "dates": "Dates",
    "payWith": "Pay with",
    "nonRefundable": "Non-refundable",
    "nonRefundableNote": "This reservation is non-refundable.",
    "groundRules": "Ground rules",
    "groundRulesNote": "We ask every guest to remember a few simple things about what makes a great guest.",
    "priceDetails": "Price Details",
    "longStayDiscount": "Long stay discount",
    "total": "Total",

        "bookingOptions": "Booking Options",
    "showMore": "Show more",
    "typeOfPlace": "Type of place",
    "anyType": "Any type",
    "rooms": "Rooms",
    "entireHome": "Entire home",
    "priceRange": "Price Range",
    "nightlyPrices": "Nightly prices before fees and taxes",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "roomsAndBeds": "Rooms and beds",
    "bathrooms": "Bathrooms",
    "amenities": "Amenities",
    
    "kitchen": "Kitchen",
    "washer": "Washer",
    "dryer": "Dryer",
    "airConditioning": "Air conditioning",
    "heating": "Heating",
    "instantBook": "Instant book",
    "selfCheckIn": "Self check-in",
    "freeCancellation": "Free cancellation",
    "allowPets": "Allow pets",
    "standoutStays": "Standout stays",
    "guestFavourite": "Guest favourite",
    "mostLovedHomes": "The most loved homes on Airbnb",
    "propertyType": "Property type",
    "accessibilityFeatures": "Accessibility features",
    "hostLanguage": "Host language",
    "clearAll": "Clear all",
    "show": "Show",
    "firstName": "First Name",
        "lastName": "Last Name",
    "searchByRegion": "Search by region",
        "imFlexible": "I'm flexible",
        "europe": "Europe",
        "italy": "Italy",
        "unitedStates": "United States",
        "greece": "Greece",
        "southeastAsia": "Southeast Asia",

        "welcomeToAirbnb": "Welcome to Airbnb",
        "email": "Email",
        "password": "Password",
        "messageAndDataRates": "We’ll call or text you to confirm your number. Standard message and data rates apply.",
        "continueWith": "Continue with",
        "search": "Search",
        "whenIsYourTrip": "When is your trip?",
        "whereYoullBe": "Where you’ll be"
},
    "ar": {
        "whereYoullBe": "أين ستكون",
        "Account": "حساب",
    "Learn_More": "تعلم أكثر",
        "personalInfo": "المعلومات الشخصية",
        "provideDetails": "قدم تفاصيل شخصية وكيف يمكننا التواصل معك",
        "loginSecurity": "تسجيل الدخول والأمان",
        "updatePassword": "تحديث كلمة المرور الخاصة بك وتأمين حسابك",
        "paymentsPayouts": "المدفوعات والمدفوعات",
        "reviewPayments": "راجع المدفوعات والمدفوعات والقسائم وبطاقات الهدايا",
        "viewWishlist": "عرض قائمة رغباتك المحبوبة",
        "seeUpcomingTrips": "انظر رحلاتك القادمة",
        "when":"متى",
        "firstName": "الاسم الأول",
        "lastName": "اسم العائلة",
"bookingOptions": "خيارات الحجز",
    "showMore": "عرض المزيد",
    "confirmAndPay": "تأكيد والدفع",
    "yourTrip": "رحلتك",
    "dates": "التواريخ",
    "payWith": "الدفع باستخدام",
    "nonRefundable": "غير قابل للاسترداد",
    "nonRefundableNote": "هذه الحجز غير قابل للاسترداد.",
    "groundRules": "قواعد أساسية",
    "groundRulesNote": "نطلب من كل ضيف أن يتذكر بعض الأشياء البسيطة حول ما يجعل الضيف جيدًا.",
    "priceDetails": "تفاصيل السعر",
    "longStayDiscount": "خصم الإقامة الطويلة",
    "total": "الإجمالي",
    "Where_to":"الى اين؟",
    "messages":"رسائل",
    "account": "الحساب",
    "explore":"أستكشاف",
     "chooseLangRegion": "اختر لغة ومنطقة",
      "filterBtnLabel": "عوامل التصفية",
      "log_out": "تسجيل الخروج",
      "taxesSwitchLabel": "عرض الإجمالي قبل الضرائب",
      "stays": "الإقامات",
      "experiences": "التجارب",
      "log_in": "تسجيل الدخول",
      "sign_up": "إنشاء حساب",
      "Wishlist": "مختاراتك المفضلة",
      "Trips": "الرحلات",
      "gift_cards": "بطاقات الهدايا",
      "airbnb_your_home": "سعر منزلك",
      "host_exp": "استضافة تجربة",
      "help_center": "مركز المساعدة",
      "who": "من",
      "addGuests": "إضافة ضيوف",
      "checkOut": "تسجيل المغادرة",
      "addDate": "إضافة تاريخ",
      "checkIn": "تسجيل الوصول",
      "where": "أين",
      "searchDest": "البحث عن الوجهات",
      "lovedBnb": "واحدة من أكثر المنازل المحبوبة على Airbnb وفقًا للضيوف",
      "reviews": "المراجعات",
      "hosted": "استضافه بيافي",
      "hostSpan": "3 أشهر من الاستضافة",
      "roomInHome": "غرفتك الخاصة في المنزل، بالإضافة إلى الوصول إلى المساحات المشتركة.",
      "sharedSpaces": "ستشارك أجزاء من المنزل مع ضيوف آخرين.",
      "prvSpace": "يوجد حمام متصل بغرفتك.",
      "grtExp": "100٪ من الضيوف حديثي الحجز قيموا عملية تسجيل الوصول بـ 5 نجوم.",
      "guestFav": "مفضل الضيوف",
      "oneOfMost": "واحدة من أكثر المنازل المحبوبة على Airbnb بناءً على التقييمات والمراجعات والموثوقية",
      "ovrAll": "التقييم العام",
      "clean": "النظافة",
      "accuracy": "الدقة",
      "check_in": "تسجيل الوصول",
      "comm": "الاتصال",
      "loc": "الموقع",
      "val": "القيمة",
      "entire": "منزل كامل",
      "in": "في",
      "guests": "ضيوف",
      "bedrooms": "غرف النوم",
      "beds": "أسرة",
      "baths": "حمامات",
      "night": "ليلة",
      "adults": "البالغون",
      "children": "الأطفال",
      "infants": "الرضع",
      "pet": "حيوان أليف",
      "notCharged": "لن يتم تحصيل رسوم بعد",
      "totalBefore": "الإجمالي قبل الضرائب",
      "reserve": "احجز",
      "showAll": "عرض جميع الصور",
      "new_roomInHome": "غرفة في المنزل",
      "new_sharedSpaces": "مساحات مشتركة",
      "new_prvSpace": "حمام خاص متصل",
      "new_grtExp": "تجربة تسجيل وصول رائعة",
      "lockOnDoor": "قفل على باب غرفة النوم",
        "wifi": "واي فاي",
        "petsAllowed": "مسموح بالحيوانات الأليفة",
        "airConditioning": "تكييف الهواء",
        "longTermStays": "الإقامات الطويلة مسموح بها",
        "lakeAccess": "الوصول إلى البحيرة",
        "freeParking": "موقف سيارات مجاني في الموقع",
        "tv": "تلفاز",
        "securityCameras": "كاميرات مراقبة في العقار",
        "cleaningAvailable": "التنظيف متاح أثناء الإقامة",
        "whatThisPlaceOffers": "ما يقدمه هذا المكان",
    "showAllAmenities": "عرض جميع وسائل الراحة",
    "meetYourHost": "تعرف على المضيف",
    "rating": "التقييم",
    "hosting": "الاستضافة",
    "years": "سنوات",
    "anywhere": "أي مكان",
    "anyWeek": "أي أسبوع",
    "addGuests": "إضافة ضيوف",
    "speaks": "يتحدث الإنجليزية، الفرنسية والهندية",
    "livesIn": "يعيش في جايبور، الهند",
    "hostBio": "مرحبًا جميعًا، أنا بيافا جاين من شركة Le Pensions Stays & Enterprises Pvt Ltd. بحكم المؤهلات، أنا محاسب قانوني من معهد المحاسبين القانونيين في الهند. ولكن في القلب، كنت دائمًا رائدة أعمال. يتمتع فريقنا بخبرة جماعية تزيد عن 24 عامًا في مجال الضيافة ونحب ما نقوم به. Le Pension...",
    "privacy": "الخصوصية",
    "terms": "الشروط",
    "siteMap": "خريطة الموقع",
        "search": "بحث",
        "whenIsYourTrip": "متى رحلتك؟",

    "typeOfPlace": "نوع المكان",
    "anyType": "أي نوع",
    "rooms": "الغرف",
    "entireHome": "منزل كامل",
    "priceRange": "نطاق السعر",
    "nightlyPrices": "أسعار الليلة قبل الرسوم والضرائب",
    "minimum": "الحد الأدنى",
    "maximum": "الحد الأقصى",
    "roomsAndBeds": "الغرف والأسرة",
    "bathrooms": "الحمامات",
    "amenities": "وسائل الراحة",
    
    "kitchen": "المطبخ",
    "washer": "غسالة",
    "dryer": "مجفف",
    "airConditioning": "تكييف الهواء",
    "heating": "التدفئة",
    "instantBook": "الحجز الفوري",
    "selfCheckIn": "تسجيل دخول ذاتي",
    "freeCancellation": "إلغاء مجاني",
    "allowPets": "السماح بالحيوانات الأليفة",
    "standoutStays": "إقامات متميزة",
    "guestFavourite": "مفضل الضيوف",
    "mostLovedHomes": "أكثر المنازل المحبوبة على Airbnb",
    "propertyType": "نوع العقار",
    "accessibilityFeatures": "ميزات إمكانية الوصول",
    "hostLanguage": "لغة المضيف",
    "clearAll": "مسح الكل",
    "show": "عرض",
    "searchByRegion": "البحث حسب المنطقة",
        "imFlexible": "أنا مرن",
        "europe": "أوروبا",
        "italy": "إيطاليا",
        "unitedStates": "الولايات المتحدة",
        "greece": "اليونان",
        "southeastAsia": "جنوب شرق آسيا",


        "welcomeToAirbnb": "مرحبًا بك في Airbnb",
        "email": "البريد الإلكتروني",
        "password": "كلمة المرور",
        "messageAndDataRates": "سنتصل بك أو نرسل لك رسالة نصية لتأكيد رقمك. تنطبق أسعار الرسائل والبيانات القياسية.",
        "continueWith": "المتابعة باستخدام",
        
},
"es": {
    "whereYoullBe": "Donde estarás",
    "Account": "Cuenta",
    "Learn_More": "Aprender más",
    "personalInfo": "Información personal",
        "provideDetails": "Proporcione detalles personales y cómo podemos comunicarnos con usted",
        "loginSecurity": "Inicio de sesión y seguridad",
        "updatePassword": "Actualice su contraseña y asegure su cuenta",
        "paymentsPayouts": "Pagos y cobros",
        "reviewPayments": "Revise pagos, cobros, cupones y tarjetas de regalo",
        "viewWishlist": "Ver su lista de deseos querida",
        "seeUpcomingTrips": "Ver sus próximos viajes",
    "when":"cuando",
    "firstName": "Nombre",
        "lastName": "Apellido",
        "filterBtnLabel": "Filtros",
        "taxesSwitchLabel": "Mostrar total antes de impuestos",
        "stays": "estancias",
        "experiences": "experiencias",
        "log_in": "iniciar sesión",
        "sign_up": "registrarse",
        "gift_cards": "tarjetas de regalo",
        "airbnb_your_home": "airbnb tu hogar",
        "Wishlist": "Lista de deseos",
        "Trips": "Viajes",
        "host_exp": "anfitrionar una experiencia",
        "messages": "Mensajes",
        "account": "Cuenta",
        "help_center": "centro de ayuda",
        "who": "quién",
        "addGuests": "añadir huéspedes",
        "checkOut": "salir",
        "addDate": "agregar fecha",
        "checkIn": "registrarse",
        "where": "dónde",
        "Where_to": "¿Dónde?",
        "search": "Buscar",
        "whenIsYourTrip": "¿Cuándo es tu viaje?",
        "searchDest": "Buscar destinos",
        "lovedBnb": "Uno de los hogares más queridos en Airbnb, según los huéspedes",
        "reviews": "Comentarios",
        "hosted": "Anfitrionado por Piavi",
        "hostSpan": "3 meses de alojamiento",
        "roomInHome": "Tu propia habitación en una casa, más acceso a espacios compartidos.",
        "sharedSpaces": "Compartirás partes de la casa con otros huéspedes.",
        "prvSpace": "Este lugar tiene un baño que está conectado a tu habitación.",
        "grtExp": "El 100% de los huéspedes recientes dieron a la experiencia de check-in una calificación de 5 estrellas.",
        "guestFav": "Favorito de los huéspedes",
        "oneOfMost": "Uno de los hogares más queridos en Airbnb basado en calificaciones, comentarios y confiabilidad",
        "ovrAll": "Calificación general",
        "clean": "Limpieza",
        "accuracy": "Exactitud",
        "check-in": "Registro",
        "comm": "Comunicación",
        "loc": "Ubicación",
        "val": "Valor",
        "entire": "Todo",
        "in": "en",
        "guests": "huéspedes",
        "bedrooms": "dormitorios",
        "beds": "camas",
        "baths": "baños",
        "night": "noche",
        "adults": "Adultos",
        "children": "Niños",
        "infants": "Infantes",
        "pet": "Mascota",
        "notCharged": "Aún no se te cobrará",
        "totalBefore": "Total antes de impuestos",
        "reserve": "Reservar",
        "showAll": "Mostrar todas las fotos",
        "log_out": "Cerrar sesión",
        "new_roomInHome": "Habitación en un hogar",
        "new_sharedSpaces": "Espacios comunes compartidos",
        "new_prvSpace": "Baño privado adjunto",
        "new_grtExp": "Gran experiencia de registro",
        "lockOnDoor": "Cerradura en la puerta del dormitorio",
        "wifi": "Wifi",
        "petsAllowed": "Se permiten mascotas",
        "airConditioning": "Aire acondicionado",
        "longTermStays": "Se permiten estancias a largo plazo",
        "lakeAccess": "Acceso al lago",
        "freeParking": "Estacionamiento gratuito en las instalaciones",
        "tv": "TV",
        "securityCameras": "Cámaras de seguridad en la propiedad",
        "cleaningAvailable": "Limpieza disponible durante la estancia",
        "whatThisPlaceOffers": "Lo que ofrece este lugar",
        "showAllAmenities": "Mostrar todas las comodidades",
        "meetYourHost": "Conoce a tu anfitrión",
        "rating": "Calificación",
        "hosting": "Alojamiento",
        "years": "Años",
        "speaks": "Habla inglés, francés e hindi",
        "livesIn": "Vive en Jaipur, India",
        "hostBio": "Hola a todos, soy Piava Jain de Le Pensions Stays & Enterprises Pvt Ltd. Por cualificación, soy contadora pública del Instituto de Contadores Públicos de India. Pero en el fondo, siempre he sido una emprendedora. Nuestro equipo tiene más de 24 años de experiencia en hospitalidad y nos encanta lo que hacemos. Le Pension...",
        "anywhere": "Cualquier lugar",
        "anyWeek": "Cualquier semana",
        "addGuests": "Añadir huéspedes",
        "privacy": "Privacidad",
        "terms": "Términos",
        "siteMap": "Mapa del sitio",
        "explore": "Explorar",
        "confirmAndPay": "Confirmar y pagar",
        "yourTrip": "Tu viaje",
        "dates": "Fechas",
        "payWith": "Pagar con",
        "nonRefundable": "No reembolsable",
        "nonRefundableNote": "Esta reserva no es reembolsable.",
        "groundRules": "Reglas básicas",
        "groundRulesNote": "Pedimos a cada huésped que recuerde algunas cosas simples sobre lo que hace a un buen huésped.",
        "priceDetails": "Detalles del precio",
        "longStayDiscount": "Descuento por estancias largas",
        "total": "Total",

        "bookingOptions": "Opciones de reserva",
        "showMore": "Mostrar más",
        "typeOfPlace": "Tipo de lugar",
        "anyType": "Cualquier tipo",
        "rooms": "Habitaciones",
        "entireHome": "Casa completa",
        "priceRange": "Rango de precios",
        "nightlyPrices": "Precios por noche antes de tarifas e impuestos",
        "minimum": "Mínimo",
        "maximum": "Máximo",
        "roomsAndBeds": "Habitaciones y camas",
        "bathrooms": "Baños",
        "amenities": "Comodidades",

        "kitchen": "Cocina",
        "washer": "Lavadora",
        "dryer": "Secadora",
        "heating": "Calefacción",
        "instantBook": "Reserva instantánea",
        "selfCheckIn": "Registro automático",
        "freeCancellation": "Cancelación gratuita",
        "allowPets": "Permitir mascotas",
        "standoutStays": "Estancias destacadas",
        "guestFavourite": "Favorito de los huéspedes",
        "mostLovedHomes": "Las casas más queridas en Airbnb",
        "propertyType": "Tipo de propiedad",
        "accessibilityFeatures": "Características de accesibilidad",
        "hostLanguage": "Idioma del anfitrión",
        "clearAll": "Limpiar todo",
        "show": "Mostrar",
        "searchByRegion": "Buscar por región",
        "imFlexible": "Soy flexible",
        "europe": "Europa",
        "italy": "Italia",
        "unitedStates": "Estados Unidos",
        "greece": "Grecia",
        "southeastAsia": "Sudeste Asiático",

        "welcomeToAirbnb": "Bienvenido a Airbnb",
        "email": "Correo electrónico",
        "password": "Contraseña",
        "messageAndDataRates": "Te llamaremos o enviaremos un mensaje para confirmar tu número. Se aplican tarifas estándar de mensajes y datos.",
        "continueWith": "Continuar con"
    },
    "fr": {
        "whereYoullBe": "Où vous serez",
        "Account": "Compte",
    "Learn_More": "En savoir plus",
        "personalInfo": "Informations personnelles",
        "provideDetails": "Fournissez des informations personnelles et comment nous pouvons vous joindre",
        "loginSecurity": "Connexion et sécurité",
        "updatePassword": "Mettez à jour votre mot de passe et sécurisez votre compte",
        "paymentsPayouts": "Paiements et paiements",
        "reviewPayments": "Examinez les paiements, les paiements, les coupons et les cartes-cadeaux",
        "viewWishlist": "Voir votre liste de souhaits bien-aimée",
        "seeUpcomingTrips": "Voir vos prochains voyages",
        "firstName": "Prénom",
        "lastName": "Nom de famille",
        "search": "Rechercher",
        "whenIsYourTrip": "Quand est votre voyage ?",
        "when":"quand",
      "filterBtnLabel": "Filtres",
      "taxesSwitchLabel": "Afficher le total avant taxes",
      "stays": "séjours",
      "experiences": "expériences",
      "log_in": "se connecter",
      "sign_up": "s'inscrire",
      "gift_cards": "cartes-cadeaux",
      "airbnb_your_home": "airbnb votre maison",
      "Wishlist": "Liste de souhaits",
      "Trips": "Voyages",
      "host_exp": "animer une expérience",
      "messages": "Messages",
      "account": "Compte",
      "help_center": "centre d'aide",
      "who": "qui",
      "addGuests": "ajouter des invités",
      "checkOut": "vérifier",
      "addDate": "ajouter une date",
      "checkIn": "enregistrer",
      "where": "où",
      "Where_to": "Où aller ?",
      "searchDest": "Rechercher des destinations",
      "lovedBnb": "Une des maisons les plus appréciées sur Airbnb, selon les invités",
      "reviews": "Avis",
      "hosted": "Animé par Piavi",
      "hostSpan": "3 mois d'hébergement",
      "roomInHome": "Votre propre chambre dans une maison, plus accès aux espaces partagés.",
      "sharedSpaces": "Vous partagerez des parties de la maison avec d'autres invités.",
      "prvSpace": "Cet endroit a une salle de bain connectée à votre chambre.",
      "grtExp": "100 % des invités récents ont donné une note de 5 étoiles au processus d'enregistrement.",
      "guestFav": "Préféré des invités",
      "oneOfMost": "Une des maisons les plus appréciées sur Airbnb selon les notes, les avis et la fiabilité",
      "ovrAll": "Note générale",
      "clean": "Propreté",
      "accuracy": "Précision",
      "check-in": "Enregistrement",
      "comm": "Communication",
      "loc": "Emplacement",
      "val": "Valeur",
      "entire": "Entier",
      "in": "dans",
      "guests": "invités",
      "bedrooms": "chambres",
      "beds": "lits",
      "baths": "bains",
      "night": "nuit",
      "adults": "Adultes",
      "children": "Enfants",
      "infants": "Bébés",
      "pet": "Animal de compagnie",
      "notCharged": "Vous ne serez pas encore facturé",
      "totalBefore": "Total avant taxes",
      "reserve": "Réserver",
      "showAll": "Afficher toutes les photos",
      "log_out": "Se déconnecter",
      "new_roomInHome": "Chambre dans une maison",
      "new_sharedSpaces": "Espaces communs partagés",
      "new_prvSpace": "Salle de bain privée attenante",
      "new_grtExp": "Excellente expérience d'enregistrement",
      "lockOnDoor": "Verrou sur la porte de la chambre",
      "wifi": "Wifi",
      "petsAllowed": "Animaux autorisés",
      "airConditioning": "Climatisation",
      "longTermStays": "Séjours de longue durée autorisés",
      "lakeAccess": "Accès au lac",
      "freeParking": "Parking gratuit sur place",
      "tv": "TV",
      "securityCameras": "Cameras de sécurité sur la propriété",
      "cleaningAvailable": "Nettoyage disponible pendant le séjour",
      "whatThisPlaceOffers": "Ce que cet endroit offre",
      "showAllAmenities": "Afficher toutes les commodités",
      "meetYourHost": "Rencontrez votre hôte",
      "rating": "Évaluation",
      "hosting": "Hébergement",
      "years": "Années",
      "speaks": "Parle anglais, français et hindi",
      "livesIn": "Vit à Jaipur, Inde",
      "hostBio": "Bonjour à tous, je suis Piava Jain de Le Pensions Stays & Enterprises Pvt Ltd. Par qualification, je suis un comptable agréé de l'Institut des comptables agréés de l'Inde. Mais dans mon cœur, j'ai toujours été un entrepreneur. Notre équipe a une expérience collective de plus de 24 ans dans l'hôtellerie et nous aimons ce que nous faisons. Le Pension...",
      "anywhere": "N'importe où",
      "anyWeek": "N'importe quelle semaine",
      "addGuests": "Ajouter des invités",
      "privacy": "Confidentialité",
      "terms": "Conditions",
      "siteMap": "Plan du site",
      "explore": "Explorer",
      "confirmAndPay": "Confirmer et payer",
      "yourTrip": "Votre voyage",
      "dates": "Dates",
      "payWith": "Payer avec",
      "nonRefundable": "Non remboursable",
      "nonRefundableNote": "Cette réservation est non remboursable.",
      "groundRules": "Règles de base",
      "groundRulesNote": "Nous demandons à chaque invité de se souvenir de quelques choses simples qui font un bon invité.",
      "priceDetails": "Détails du prix",
      "longStayDiscount": "Remise pour un séjour prolongé",
      "total": "Total",
      "bookingOptions": "Options de réservation",
      "showMore": "Afficher plus",
      "typeOfPlace": "Type de lieu",
      "anyType": "Tout type",
      "rooms": "Chambres",
      "entireHome": "Maison entière",
      "priceRange": "Plage de prix",
      "nightlyPrices": "Prix par nuit avant frais et taxes",
      "minimum": "Minimum",
      "maximum": "Maximum",
      "roomsAndBeds": "Chambres et lits",
      "bathrooms": "Salles de bains",
      "amenities": "Commodités",
      "kitchen": "Cuisine",
      "washer": "Lave-linge",
      "dryer": "Sèche-linge",
      "heating": "Chauffage",
      "instantBook": "Réservation instantanée",
      "selfCheckIn": "Enregistrement autonome",
      "freeCancellation": "Annulation gratuite",
      "allowPets": "Autoriser les animaux",
      "standoutStays": "Séjours remarquables",
      "guestFavourite": "Préféré des invités",
      "mostLovedHomes": "Les maisons les plus aimées sur Airbnb",
      "propertyType": "Type de propriété",
      "accessibilityFeatures": "Caractéristiques d'accessibilité",
      "hostLanguage": "Langue de l'hôte",
      "clearAll": "Tout effacer",
      "show": "Montrer",
      "searchByRegion": "Recherche par région",
        "imFlexible": "Je suis flexible",
        "europe": "Europe",
        "italy": "Italie",
        "unitedStates": "États-Unis",
        "greece": "Grèce",
        "southeastAsia": "Asie du Sud-Est",

        "welcomeToAirbnb": "Bienvenue sur Airbnb",
        "email": "E-mail",
        "password": "Mot de passe",
        "messageAndDataRates": "Nous vous appellerons ou vous enverrons un message pour confirmer votre numéro. Des frais standards de message et de données peuvent s'appliquer.",
        "continueWith": "Continuer avec Facebook",
        
    }
  };
  
  export default languages;
  