const langs = {
  en: {
    Account: "Account",
    Learn_More: "Learn more",
    Wishlist: "Wishlist",
    Trips: "Trips",
    personalInfo: "Personal info",
    loginSecurity: "Login & security",
    paymentsPayouts: "Payments & payouts",
    provideDetails: "Provide details to personalize your account",
    updatePassword: "Update your password to keep your account secure",
    reviewPayments: "Review payments, payouts, and any gift cards",
    viewWishlist: "View the listings you have saved",
    seeUpcomingTrips: "See your upcoming and past trips",
    privacy: "Privacy",
    terms: "Terms",
    siteMap: "Sitemap",
    anywhere: "Anywhere",
    anyWeek: "Any week",
    addGuests: "Add guests",
    search: "Search",
    whenIsYourTrip: "When's your trip?",
    imFlexible: "I'm flexible",
    europe: "Europe",
    italy: "Italy",
    unitedStates: "United States",
    greece: "Greece",
    southeastAsia: "Southeast Asia",
    Where_to: "Where to?",
    searchDest: "Search destinations",
    searchByRegion: "Search by region",
    chooseLangRegion: "Choose a language and region",
    where: "Where",
    who: "Who",
    guests: "guests",
    adults: "Adults",
    children: "Children",
    infants: "Infants",
    petsAllowed: "Pets allowed",
    addDate: "Add dates",
    checkIn: "Check in",
    checkOut: "Check out",
    dates: "Dates",
    night: "night",
    entire: "Entire place",
    entireHome: "Entire home",
    rooms: "Rooms",
    in: "in",
    bathrooms: "Bathrooms",
    baths: "baths",
    bedrooms: "bedrooms",
    beds: "beds",
    oneOfMost: "One of the most loved homes on Airbnb",
    reviews: "reviews",
    hosted: "Hosted by",
    hostSpan: "Years of hosting experience",
    roomInHome: "A room in a home, just for you",
    sharedSpaces: "Shared common spaces",
    prvSpace: "Private attached bathroom",
    grtExp: "Great check-in experience",
    new_roomInHome: "new",
    new_sharedSpaces: "new",
    new_prvSpace: "new",
    new_grtExp: "new",
    guestFav: "Guest favourite",
    ovrAll: "Overall rating",
    clean: "Cleanliness",
    accuracy: "Accuracy",
    check_in: "Check-in",
    comm: "Communication",
    loc: "Location",
    val: "Value",
    whereYoullBe: "Where you'll be",
    showAll: "Show all",
    showAllAmenities: "Show all amenities",
    whatThisPlaceOffers: "What this place offers",
    tv: "TV",
    wifi: "Wifi",
    kitchen: "Kitchen",
    washer: "Washer",
    dryer: "Dryer",
    airConditioning: "Air conditioning",
    heating: "Heating",
    freeParking: "Free parking",
    lakeAccess: "Lake access",
    lockOnDoor: "Lock on bedroom door",
    securityCameras: "Security cameras",
    typeOfPlace: "Type of place",
    anyType: "Any type",
    priceRange: "Price range",
    nightlyPrices: "Nightly prices",
    minimum: "Minimum",
    maximum: "Maximum",
    roomsAndBeds: "Rooms and beds",
    amenities: "Amenities",
    bookingOptions: "Booking options",
    standoutStays: "Standout stays",
    guestFavourite: "Guest favourite",
    mostLovedHomes: "The most loved homes, according to guests",
    propertyType: "Property type",
    accessibilityFeatures: "Accessibility features",
    hostLanguage: "Host language",
    clearAll: "Clear all",
    show: "Show",
    showMore: "Show more",
    filterBtnLabel: "Filters",
    instantBook: "Instant Book",
    selfCheckIn: "Self check-in",
    freeCancellation: "Free cancellation",
    allowPets: "Allows pets",
    confirmAndPay: "Confirm and pay",
    yourTrip: "Your trip",
    payWith: "Pay with",
    nonRefundable: "Non-refundable",
    nonRefundableNote: "This host's cancellation policy is non-refundable. Any payment will not be refunded.",
    groundRules: "Ground rules",
    groundRulesNote: "We ask every guest to remember a few simple things about what makes a great guest.",
    priceDetails: "Price details",
    longStayDiscount: "Long stay discount",
    total: "Total",
    totalBefore: "Total before taxes",
    taxesSwitchLabel: "Show taxes",
    notCharged: "You won't be charged yet",
    reserve: "Reserve",
    meetYourHost: "Meet your host",
    livesIn: "Lives in",
    speaks: "Speaks",
    years: "years",
    hostBio: "Host bio",
    host_exp: "Host experience",
    messageAndDataRates: "Message and data rates may apply",
    continueWith: "Continue with",
    log_in: "Log in",
    sign_up: "Sign up",
    email: "Email",
    password: "Password",
    firstName: "First name",
    lastName: "Last name",
    hosting: "Hosting",
    experiences: "Experiences",
    airbnb_your_home: "Airbnb your home",
    gift_cards: "Gift cards",
    help_center: "Help Center",
    explore: "Explore",
    stays: "Stays",
    longTermStays: "Long term stays",
    rating: "Rating",
    messages: "Messages",
  },
  ar: {
    Account: "الحساب",
    Learn_More: "اعرف المزيد",
    Wishlist: "المفضلة",
    Trips: "الرحلات",
    personalInfo: "المعلومات الشخصية",
    loginSecurity: "تسجيل الدخول والأمان",
    paymentsPayouts: "المدفوعات والأرباح",
    provideDetails: "قدم التفاصيل لتخصيص حسابك",
    updatePassword: "حدّث كلمة المرور للحفاظ على أمان حسابك",
    reviewPayments: "راجع المدفوعات والأرباح وبطاقات الهدايا",
    viewWishlist: "عرض القوائم التي حفظتها",
    seeUpcomingTrips: "شاهد رحلاتك القادمة والسابقة",
    privacy: "الخصوصية",
    terms: "الشروط",
    siteMap: "خريطة الموقع",
    anywhere: "أي مكان",
    anyWeek: "أي أسبوع",
    addGuests: "أضف الضيوف",
    search: "بحث",
    whenIsYourTrip: "متى رحلتك؟",
    imFlexible: "أنا مرن",
    europe: "أوروبا",
    italy: "إيطاليا",
    unitedStates: "الولايات المتحدة",
    greece: "اليونان",
    southeastAsia: "جنوب شرق آسيا",
    Where_to: "إلى أين؟",
    searchDest: "ابحث عن وجهات",
    searchByRegion: "البحث حسب المنطقة",
    chooseLangRegion: "اختر اللغة والمنطقة",
    where: "أين",
    who: "من",
    guests: "ضيوف",
    adults: "البالغون",
    children: "الأطفال",
    infants: "الرضع",
    petsAllowed: "يُسمح بالحيوانات الأليفة",
    addDate: "أضف التواريخ",
    checkIn: "تسجيل الوصول",
    checkOut: "تسجيل المغادرة",
    dates: "التواريخ",
    night: "ليلة",
    entire: "المكان بالكامل",
    entireHome: "منزل بالكامل",
    rooms: "الغرف",
    in: "في",
    bathrooms: "الحمامات",
    baths: "حمامات",
    bedrooms: "غرف نوم",
    beds: "أسرّة",
    oneOfMost: "واحد من أكثر المنازل المحبوبة على Airbnb",
    reviews: "تقييمات",
    hosted: "يستضيفه",
    hostSpan: "سنوات من الخبرة في الاستضافة",
    roomInHome: "غرفة في منزل، لك وحدك",
    sharedSpaces: "مساحات مشتركة",
    prvSpace: "حمام خاص ملحق",
    grtExp: "تجربة تسجيل وصول رائعة",
    new_roomInHome: "جديد",
    new_sharedSpaces: "جديد",
    new_prvSpace: "جديد",
    new_grtExp: "جديد",
    guestFav: "مفضل الضيوف",
    ovrAll: "التقييم الإجمالي",
    clean: "النظافة",
    accuracy: "الدقة",
    check_in: "تسجيل الوصول",
    comm: "التواصل",
    loc: "الموقع",
    val: "القيمة",
    whereYoullBe: "أين ستكون",
    showAll: "عرض الكل",
    showAllAmenities: "عرض جميع وسائل الراحة",
    whatThisPlaceOffers: "ما يقدمه هذا المكان",
    tv: "تلفاز",
    wifi: "واي فاي",
    kitchen: "مطبخ",
    washer: "غسالة",
    dryer: "مجفف",
    airConditioning: "تكييف هواء",
    heating: "تدفئة",
    freeParking: "موقف سيارات مجاني",
    lakeAccess: "إمكانية الوصول إلى البحيرة",
    lockOnDoor: "قفل على باب غرفة النوم",
    securityCameras: "كاميرات مراقبة",
    typeOfPlace: "نوع المكان",
    anyType: "أي نوع",
    priceRange: "نطاق السعر",
    nightlyPrices: "أسعار الليلة",
    minimum: "الحد الأدنى",
    maximum: "الحد الأقصى",
    roomsAndBeds: "الغرف والأسرّة",
    amenities: "وسائل الراحة",
    bookingOptions: "خيارات الحجز",
    standoutStays: "إقامات مميزة",
    guestFavourite: "مفضل الضيوف",
    mostLovedHomes: "المنازل الأكثر محبة، وفقًا للضيوف",
    propertyType: "نوع العقار",
    accessibilityFeatures: "ميزات إمكانية الوصول",
    hostLanguage: "لغة المضيف",
    clearAll: "مسح الكل",
    show: "عرض",
    showMore: "عرض المزيد",
    filterBtnLabel: "الفلاتر",
    instantBook: "حجز فوري",
    selfCheckIn: "تسجيل وصول ذاتي",
    freeCancellation: "إلغاء مجاني",
    allowPets: "يسمح بالحيوانات الأليفة",
    confirmAndPay: "تأكيد ودفع",
    yourTrip: "رحلتك",
    payWith: "ادفع بـ",
    nonRefundable: "غير قابل للاسترداد",
    nonRefundableNote: "سياسة الإلغاء لهذا المضيف غير قابلة للاسترداد. لن يتم استرداد أي دفعة.",
    groundRules: "القواعد الأساسية",
    groundRulesNote: "نطلب من كل ضيف تذكر بعض الأشياء البسيطة التي تجعل الضيف رائعًا.",
    priceDetails: "تفاصيل السعر",
    longStayDiscount: "خصم الإقامة الطويلة",
    total: "الإجمالي",
    totalBefore: "الإجمالي قبل الضرائب",
    taxesSwitchLabel: "عرض الضرائب",
    notCharged: "لن يتم خصم المبلغ بعد",
    reserve: "احجز",
    meetYourHost: "تعرّف على مضيفك",
    livesIn: "يعيش في",
    speaks: "يتحدث",
    years: "سنوات",
    hostBio: "نبذة عن المضيف",
    host_exp: "خبرة الاستضافة",
    messageAndDataRates: "قد تنطبق رسوم الرسائل والبيانات",
    continueWith: "المتابعة باستخدام",
    log_in: "تسجيل الدخول",
    sign_up: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    hosting: "الاستضافة",
    experiences: "التجارب",
    airbnb_your_home: "اعرض منزلك على Airbnb",
    gift_cards: "بطاقات الهدايا",
    help_center: "مركز المساعدة",
    explore: "استكشاف",
    stays: "إقامات",
    longTermStays: "إقامات طويلة الأمد",
    rating: "التقييم",
    messages: "الرسائل",
  },
};

export default langs;
